// Generated by tools/generate_contracts.py. Do not edit manually.
// The web client consumes this generated contract.

export interface AddMemoryRequest {
  memo: string;
}

export interface AddMessageRequest {
  role: "user" | "assistant" | "system";
  content: string;
  sources?: Array<unknown> | null;
  thoughts?: string | null;
}

export interface AppearanceSettings {
  theme?: "light" | "dark" | "system";
}

export interface ChatMessage {
  id?: string | null;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp?: string | null;
  sources?: Array<unknown> | null;
  thoughts?: string | null;
}

export interface ChatResponse {
  id: string;
  title: string;
  timestamp: string;
  revision?: number;
  messages?: Array<ChatMessage>;
}

export interface ChatSummary {
  id: string;
  title: string;
  timestamp: string;
}

export interface ClearMemoryRequest {
  confirm?: boolean;
}

export interface ConnectionResult {
  success: boolean;
  status: "connecting" | "connected" | "error";
  message: string;
  details?: string | null;
  missing_models?: Array<string>;
  optional_missing_models?: Array<string>;
}

export interface CortexSettings {
  schema_version?: number;
  revision?: number;
  appearance?: AppearanceSettings;
  onboarding?: OnboardingSettings;
  models?: ModelSettings;
  generation?: GenerationSettings;
  memory?: MemorySettings;
  translation?: TranslationSettings;
  suggestions?: SuggestionSettings;
}

export interface CreateChatRequest {
  title?: string;
}

export interface ForkRequest {
  message_id: string;
}

export interface GenerationEvent {
  event_id: number;
  event: "generation.queued" | "generation.started" | "generation.status" | "generation.thinking_delta" | "generation.content_delta" | "generation.translation_started" | "generation.persisting" | "generation.completed" | "generation.failed" | "generation.cancelled";
  job_id: string;
  thread_id: string;
  timestamp: string;
  data?: Record<string, unknown>;
}

export interface GenerationRequest {
  request_id?: string | null;
  thread_id?: string | null;
  user_input: string;
  base_revision?: number | null;
}

export interface GenerationSettings {
  temperature?: number;
  num_ctx?: number;
  seed?: number;
  system_instructions?: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HealthResponse {
  status?: string;
}

export interface JobAccepted {
  job_id: string;
  kind: "generation" | "models";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  thread_id?: string | null;
  user_message_id?: string | null;
}

export interface JobStatusResponse {
  job_id: string;
  kind: "generation" | "models";
  thread_id?: string | null;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  sequence: number;
  error?: string | null;
  result?: Record<string, unknown> | null;
}

export interface MemoryResponse {
  memos: Array<string>;
}

export interface MemorySettings {
  enabled?: boolean;
}

export interface ModelResponse {
  required_models: Array<string>;
  optional_models: Array<string>;
  installed_models?: Array<string>;
  missing_models?: Array<string>;
  optional_missing_models?: Array<string>;
  connection?: ConnectionResult | null;
}

export interface ModelSettings {
  chat?: string;
  title?: string;
  translation?: string;
}

export interface OnboardingSettings {
  agreement_accepted?: boolean;
}

export interface RegenerationRequest {
  request_id?: string | null;
  message_id: string;
  user_input?: string | null;
}

export interface RenameChatRequest {
  title: string;
}

export interface ReplaceMemoryRequest {
  memos: Array<string>;
}

export interface SSEEvent {
  id: number;
  job_id: string;
  kind: "state" | "progress" | "completed" | "error";
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  phase?: string | null;
  data?: Record<string, unknown>;
}

export interface SessionExchangeRequest {
  bootstrap_token: string;
}

export interface SessionExchangeResponse {
  session_token: string;
  expires_at: string;
  token_type?: string;
}

export interface SettingsResponse {
  settings: CortexSettings;
  source: string;
  invalid_keys?: Array<string>;
}

export interface SettingsUpdateRequest {
  settings: CortexSettings;
}

export interface SuggestionSettings {
  enabled?: boolean;
  model?: string;
}

export interface SystemResponse {
  api_version?: string;
  status?: string;
  preview?: boolean;
  qt_default?: boolean;
  session_required?: boolean;
  started_at: string;
}

export interface TranslationSettings {
  enabled?: boolean;
  target_language?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
