// Generated by tools/generate_contracts.py. Do not edit manually.
// The web client consumes this generated contract.

export interface AddMemoryRequest {
  memo: string;
}

export interface AddMessageRequest {
  role: "user" | "assistant" | "system";
  content: string;
  base_revision?: number | null;
  sources?: Array<unknown> | null;
  thoughts?: string | null;
  attachments?: Array<ChatAttachment> | null;
}

export interface AppearanceSettings {
  theme?: "light" | "dark" | "system";
}

export interface AttachmentStageAccepted {
  job_id: string;
  request_id: string;
  profile: "attachment.stage.v1";
  status: "succeeded";
  sequence: number;
  artifact_id: string;
  mime_type: string;
  size: number;
  sha256: string;
  expires_at: string;
}

export interface AttachmentStageRequest {
  request_id: string;
  content_base64: string;
  retention_seconds?: number;
}

export interface BrightnessStep {
  op: "brightness";
  factor: number | string;
}

export interface ChatAttachment {
  attachment_id: string;
  filename: string;
  mime_type: string;
  size: number;
  sha256: string;
  kind: "image" | "document";
  expires_at: string;
}

export interface ChatAttachmentStageRequest {
  request_id: string;
  filename: string;
  content_base64: string;
}

export interface ChatMessage {
  id?: string | null;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp?: string | null;
  sources?: Array<unknown> | null;
  thoughts?: string | null;
  attachments?: Array<ChatAttachment> | null;
}

export interface ChatResponse {
  id: string;
  title: string;
  timestamp: string;
  revision?: number;
  messages?: Array<ChatMessage>;
}

export interface ChatSummary {
  id: string;
  title: string;
  timestamp: string;
}

export interface ClearMemoryRequest {
  confirm?: boolean;
  confirmation_intent?: "clear_permanent_memory" | null;
}

export interface ConnectionResult {
  success: boolean;
  status: "connecting" | "connected" | "error";
  message: string;
  details?: string | null;
  missing_models?: Array<string>;
  optional_missing_models?: Array<string>;
}

export interface ContrastStep {
  op: "contrast";
  factor: number | string;
}

export interface CortexSettings {
  schema_version?: 1;
  revision?: number;
  appearance?: AppearanceSettings;
  onboarding?: OnboardingSettings;
  models?: ModelSettings;
  generation?: GenerationSettings;
  execution?: ExecutionSettings;
  memory?: MemorySettings;
  translation?: TranslationSettings;
  suggestions?: SuggestionSettings;
}

export interface CreateChatRequest {
  title?: string;
}

export interface CropStep {
  op: "crop";
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface DiagnosticsResponse {
  api_version?: "v1";
  settings_source: string;
  invalid_settings_keys?: Array<string>;
  migration?: SettingsMigrationReport | null;
  installed_models?: Array<string>;
  required_models?: Array<string>;
  optional_models?: Array<string>;
  connection?: ConnectionResult | null;
  ollama_host: string;
  ollama_setup_url: string;
}

export interface ExecutionAccepted {
  job_id: string;
  request_id: string;
  profile: "fake.v1";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
}

export interface ExecutionApprovalDecisionRequest {
  decision: "approved" | "denied";
}

export interface ExecutionPreviewRequest {
  request_id: string;
  outcome?: "success" | "failure";
  steps?: number;
  step_delay_seconds?: number;
}

export interface ExecutionSettings {
  automatic_compute?: boolean;
}

export interface ExecutionStatusResponse {
  job_id: string;
  request_id: string;
  profile: string;
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
  phase?: string | null;
  message?: string | null;
  approval_state?: "not_required" | "pending" | "approved" | "denied" | "expired";
  approval_reason?: string | null;
  approval_expires_at?: string | null;
  can_cancel?: boolean;
  error?: string | null;
  result?: Record<string, unknown> | null;
}

export interface ExecutionTaskListResponse {
  tasks: Array<ExecutionTaskSummary>;
}

export interface ExecutionTaskSummary {
  job_id: string;
  profile: string;
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
  phase?: string | null;
  message?: string | null;
  approval_state?: "not_required" | "pending" | "approved" | "denied" | "expired";
  approval_reason?: string | null;
  approval_expires_at?: string | null;
  can_cancel?: boolean;
  created_at: string;
  updated_at: string;
}

export interface ForkRequest {
  message_id: string;
}

export interface GenerationEvent {
  event_id: number;
  event: "generation.queued" | "generation.started" | "generation.status" | "generation.thinking_delta" | "generation.content_delta" | "generation.translation_started" | "generation.persisting" | "generation.completed" | "generation.failed" | "generation.cancelling" | "generation.cancelled";
  job_id: string;
  thread_id: string;
  timestamp: string;
  data?: Record<string, unknown>;
}

export interface GenerationRequest {
  request_id?: string | null;
  thread_id?: string | null;
  user_input: string;
  base_revision?: number | null;
  attachments?: Array<ChatAttachment>;
}

export interface GenerationSettings {
  temperature?: number;
  num_ctx?: number;
  seed?: number;
  system_instructions?: string;
}

export interface GrayscaleStep {
  op: "grayscale";
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface HandoffResponse {
  bootstrap_token: string;
  expires_at: string;
}

export interface HealthResponse {
  status?: "ok";
}

export interface ImageTransformPlan {
  schema_version: "artifact.transform.v1";
  input_artifact_id: string;
  steps: Array<GrayscaleStep | ContrastStep | BrightnessStep | CropStep | ResizeStep | RotateStep>;
  output_format: "png" | "jpeg" | "webp";
  strip_metadata?: true;
}

export interface InstalledModel {
  name: string;
  size?: number | null;
  modified_at?: string | null;
  capabilities?: Array<string>;
  supports_vision?: boolean | null;
}

export interface JobAccepted {
  job_id: string;
  kind: "generation" | "models";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  thread_id?: string | null;
  user_message_id?: string | null;
}

export interface JobStatusResponse {
  job_id: string;
  kind: "generation" | "models";
  thread_id?: string | null;
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
  error?: string | null;
  result?: Record<string, unknown> | null;
}

export interface MemoryResponse {
  memos: Array<string>;
}

export interface MemorySettings {
  enabled?: boolean;
}

export interface ModelPullRequest {
  model: string;
}

export interface ModelResponse {
  required_models: Array<string>;
  optional_models: Array<string>;
  installed_models?: Array<string>;
  missing_models?: Array<string>;
  optional_missing_models?: Array<string>;
  connection?: ConnectionResult | null;
  models?: Array<InstalledModel>;
}

export interface ModelSettings {
  chat?: string | null;
  title?: string | null;
  translation?: string;
}

export interface OnboardingSettings {
  agreement_accepted?: boolean;
}

export interface RecipeImageTransformAccepted {
  job_id: string;
  request_id: string;
  profile: "recipe.image.v1";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
}

export interface RecipeImageTransformRequest {
  request_id: string;
  source_artifact_id: string;
  plan: ImageTransformPlan;
  retention_seconds?: number;
}

export interface RegenerationRequest {
  request_id?: string | null;
  message_id: string;
  user_input?: string | null;
  base_revision?: number | null;
  attachments?: Array<ChatAttachment>;
}

export interface RenameChatRequest {
  title: string;
}

export interface ReplaceMemoryRequest {
  memos: Array<string>;
}

export interface ResizeStep {
  op: "resize";
  width: number;
  height: number;
}

export interface RotateStep {
  op: "rotate";
  degrees: 90 | 180 | 270;
}

export interface SSEEvent {
  id: number;
  job_id: string;
  kind: "state" | "progress" | "completed" | "error";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  phase?: string | null;
  data?: Record<string, unknown>;
}

export interface ScratchComputeAccepted {
  job_id: string;
  request_id: string;
  profile: "scratch.auto.v1";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  sequence: number;
}

export interface ScratchComputeRequest {
  request_id: string;
  expression: string;
}

export interface SessionExchangeRequest {
  bootstrap_token: string;
}

export interface SessionExchangeResponse {
  session_token: string;
  expires_at: string;
  token_type?: "bearer";
}

export interface SettingsMigrationReport {
  status: "not_needed" | "migrated" | "already_migrated" | "failed";
  source: string;
  migration_key?: string | null;
  imported_keys?: Array<string>;
  invalid_keys?: Array<string>;
  backup_path?: string | null;
  message?: string | null;
}

export interface SettingsResponse {
  settings: CortexSettings;
  source: string;
  present_keys?: Array<string>;
  invalid_keys?: Array<string>;
  migration?: SettingsMigrationReport | null;
}

export interface SettingsUpdateRequest {
  settings: CortexSettings;
}

export interface ShutdownResponse {
  status?: "accepted";
}

export interface SuggestionSettings {
  enabled?: boolean;
  model?: string | null;
}

export interface SystemResponse {
  api_version?: "v1";
  status?: "ok";
  preview?: boolean;
  session_required?: boolean;
  execution_preview_available?: boolean;
  scratch_compute_available?: boolean;
  image_transform_available?: boolean;
  started_at: string;
  ollama_host?: string;
  ollama_setup_url?: string;
}

export interface TranslationSettings {
  enabled?: boolean;
  target_language?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface ExecutionSSEEvent {
  id: number;
  sequence: number;
  job_id: string;
  event: "execution.queued" | "execution.started" | "execution.progress" | "execution.cancelling" | "execution.recovered" | "execution.completed" | "execution.failed" | "execution.cancelled";
  status: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
  phase?: string | null;
  data?: Record<string, unknown>;
}
