"""Durable execution primitives and provider-independent safety contracts.

Only deterministic contracts, the storage-only signed bundle installer, and the
reviewed broker transports are exposed in this phase. Native transport and bundle
storage never load a provider; real runtime providers stay absent until later ADR
gates are approved.
"""

from .broker import (
    BrokerAclPolicy,
    BrokerFrame,
    BrokerFrameDecoder,
    BrokerMessage,
    BrokerPeerPolicy,
    BrokerProtocolError,
    BrokerSessionKeys,
    PeerIdentity,
    authorize_message,
    decode_frame,
    decode_message,
    encode_frame,
    encode_message,
)
from .artifact_boundary import (
    ArtifactBoundary,
    ArtifactBoundaryError,
    ArtifactSourceGrant,
    MAX_ARTIFACT_PATH_CHARS,
    MAX_OUTPUT_COUNT,
    OutputClaim,
    PublishedArtifact,
    sniff_artifact_mime,
)
from .fake import FakeExecutionPlan, FakeExecutionProvider
from .bundle_installer import (
    BundleInstallError,
    BundleRecord,
    InstalledBundle,
    KeyringUpdate,
    RollbackAuthorizer,
    SignedBundleInstaller,
    parse_keyring_update,
    verify_keyring_update,
)
from .lifecycle import ExecutionLifecycle, LifecycleSnapshot, RuntimeHealth
from .manifest import (
    ManifestEntry,
    ManifestState,
    ManifestVerificationError,
    SignedRecipeManifest,
    TrustedRecipeKeys,
    VerifiedRecipeManifest,
    parse_signed_manifest,
    verify_bundle_files,
    verify_manifest_signature,
    verify_signed_manifest,
)
from .native_broker import (
    DEFAULT_NATIVE_CONNECT_TIMEOUT_MS,
    DEFAULT_NATIVE_PIPE_BUFFER_BYTES,
    MAX_NATIVE_PIPE_NAME_LENGTH,
    NativeBrokerClient,
    NativeBrokerClientConfig,
    NativeBrokerConnection,
    NativeBrokerError,
    NativeBrokerServer,
    NativeBrokerServerConfig,
    build_pipe_sddl,
)
from .native_launcher import (
    BrokerWorkerBinding,
    BrokerWorkerBinder,
    NativeLauncherError,
    NativeProcessFactory,
    NativeSuspendedWorker,
    NativeWorkerLaunchPlan,
    NativeWorkerLauncher,
    NativeWorkerPolicy,
)
from .worker_provenance import (
    EXPECTED_WORKER_PATH,
    VerifiedRecipeWorker,
    WorkerProvenanceError,
    verify_active_worker,
    verify_installed_worker,
)
from .recipes import (
    CalculatorPlan,
    CheckPlan,
    ImageTransformPlan,
    PrimitiveEvaluationError,
    RecipeValidationError,
    evaluate_calculator,
    evaluate_check,
    parse_calculator,
    parse_check,
    parse_image_transform,
)
from .repository import (
    ArtifactLimitError,
    ApprovalPolicyError,
    ApprovalTransitionError,
    ExecutionRepository,
    LeaseConflict,
    ExecutionRepositoryError,
)

__all__ = [
    "ArtifactLimitError",
    "ArtifactBoundary",
    "ArtifactBoundaryError",
    "ArtifactSourceGrant",
    "ApprovalPolicyError",
    "ApprovalTransitionError",
    "BrokerAclPolicy",
    "BrokerFrame",
    "BrokerFrameDecoder",
    "BrokerMessage",
    "BrokerPeerPolicy",
    "BrokerProtocolError",
    "BrokerSessionKeys",
    "BundleInstallError",
    "BundleRecord",
    "DEFAULT_NATIVE_CONNECT_TIMEOUT_MS",
    "DEFAULT_NATIVE_PIPE_BUFFER_BYTES",
    "ExecutionRepository",
    "ExecutionRepositoryError",
    "ExecutionLifecycle",
    "CalculatorPlan",
    "CheckPlan",
    "FakeExecutionPlan",
    "FakeExecutionProvider",
    "ImageTransformPlan",
    "InstalledBundle",
    "KeyringUpdate",
    "LeaseConflict",
    "LifecycleSnapshot",
    "ManifestEntry",
    "ManifestState",
    "ManifestVerificationError",
    "MAX_ARTIFACT_PATH_CHARS",
    "MAX_OUTPUT_COUNT",
    "MAX_NATIVE_PIPE_NAME_LENGTH",
    "NativeBrokerClient",
    "NativeBrokerClientConfig",
    "NativeBrokerConnection",
    "NativeBrokerError",
    "NativeBrokerServer",
    "NativeBrokerServerConfig",
    "BrokerWorkerBinding",
    "BrokerWorkerBinder",
    "NativeLauncherError",
    "NativeProcessFactory",
    "NativeSuspendedWorker",
    "NativeWorkerLaunchPlan",
    "NativeWorkerLauncher",
    "NativeWorkerPolicy",
    "PrimitiveEvaluationError",
    "OutputClaim",
    "PublishedArtifact",
    "RecipeValidationError",
    "RuntimeHealth",
    "RollbackAuthorizer",
    "SignedBundleInstaller",
    "SignedRecipeManifest",
    "TrustedRecipeKeys",
    "VerifiedRecipeManifest",
    "evaluate_calculator",
    "evaluate_check",
    "parse_signed_manifest",
    "parse_calculator",
    "parse_check",
    "parse_image_transform",
    "sniff_artifact_mime",
    "verify_bundle_files",
    "verify_manifest_signature",
    "parse_keyring_update",
    "verify_keyring_update",
    "verify_signed_manifest",
    "PeerIdentity",
    "authorize_message",
    "build_pipe_sddl",
    "EXPECTED_WORKER_PATH",
    "VerifiedRecipeWorker",
    "WorkerProvenanceError",
    "verify_active_worker",
    "verify_installed_worker",
    "decode_frame",
    "decode_message",
    "encode_frame",
    "encode_message",
]
