"""Durable execution primitives and provider-independent safety contracts.

The package exposes deterministic contracts, the storage-only signed bundle
installer, reviewed broker transports, an optional qualification composition,
and the normal process-backed local runtime. Native transport and bundle storage
never load a provider; the normal application uses only the checked-in bounded
local profiles unless a caller explicitly selects qualification wiring.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

# The imports below are for static analysis (type checkers, IDEs) only. At
# runtime, every symbol in __all__ is resolved lazily by __getattr__ so that
# importing any one submodule of this package -- as every worker entrypoint
# does (e.g. packaging/recipe_worker/recipe_worker.py importing only
# .native_broker and .worker_runtime) -- does not force Python to also
# import the other ~20 submodules and their heavy dependencies (cryptography,
# pydantic, Pillow, ctypes) as a side effect of initializing this package.
if TYPE_CHECKING:
    from .broker import (
        BrokerAclPolicy,
        BrokerFrame,
        BrokerFrameDecoder,
        BrokerMessage,
        BrokerPeerPolicy,
        BrokerProtocolError,
        BrokerSessionKeys,
        PeerIdentity,
        authorize_message,
        decode_frame,
        decode_message,
        encode_frame,
        encode_message,
    )
    from .artifact_boundary import (
        ArtifactBoundary,
        ArtifactBoundaryError,
        ArtifactSourceGrant,
        MAX_ARTIFACT_PATH_CHARS,
        MAX_OUTPUT_COUNT,
        OutputClaim,
        PublishedArtifact,
        sniff_artifact_mime,
    )
    from .attachment_staging import (
        ATTACHMENT_PAYLOAD_SCHEMA,
        ATTACHMENT_RESULT_SCHEMA,
        ATTACHMENT_STAGE_PROFILE,
        AttachmentStageResult,
        AttachmentStagingError,
        AttachmentStagingService,
        DEFAULT_ATTACHMENT_RETENTION_SECONDS,
        MAX_ATTACHMENT_RETENTION_SECONDS,
    )
    from .fake import FakeExecutionPlan, FakeExecutionProvider
    from .bundle_installer import (
        BundleInstallError,
        BundleRecord,
        InstalledBundle,
        KeyringUpdate,
        RollbackAuthorizer,
        SignedBundleInstaller,
        parse_keyring_update,
        verify_keyring_update,
    )
    from .lifecycle import ExecutionLifecycle, LifecycleSnapshot, RuntimeHealth
    from .local_runtime import (
        DEFAULT_CODE_STARTUP_TIMEOUT_SECONDS,
        DEFAULT_CODE_TIMEOUT_SECONDS,
        LocalExecutionCoordinator,
        LocalRecipeWorkerAttempt,
    )
    from .code_execution import (
        CODE_EXECUTION_PAYLOAD_SCHEMA,
        CODE_EXECUTION_PROFILE,
        CODE_EXECUTION_RESULT_SCHEMA,
        CodeCapabilities,
        CodeExecutionError,
        CodeExecutionRequest,
        CodeExecutionResult,
        validate_code_source,
    )
    from .qualification import (
        CoordinatorFactory,
        ExecutionProfile,
        ProviderHealthProbe,
        QualificationLifecycleConfig,
        QualificationProfileError,
        build_execution_lifecycle,
        build_native_recipe_coordinator_factory,
        build_recipe_coordinator_factory,
        parse_execution_profile,
    )
    from .manifest import (
        ManifestEntry,
        ManifestState,
        ManifestVerificationError,
        SignedRecipeManifest,
        TrustedRecipeKeys,
        VerifiedRecipeManifest,
        parse_signed_manifest,
        verify_bundle_files,
        verify_manifest_signature,
        verify_signed_manifest,
    )
    from .native_broker import (
        DEFAULT_NATIVE_CONNECT_TIMEOUT_MS,
        DEFAULT_NATIVE_PIPE_BUFFER_BYTES,
        MAX_NATIVE_PIPE_NAME_LENGTH,
        NativeBrokerClient,
        NativeBrokerClientConfig,
        NativeBrokerConnection,
        NativeBrokerError,
        NativeBrokerServer,
        NativeBrokerServerConfig,
        build_pipe_sddl,
    )
    from .native_launcher import (
        BrokerWorkerBinding,
        BrokerWorkerBinder,
        NativeBrokerIdentityBinder,
        NativeLauncherError,
        NativeProcessFactory,
        NativeSuspendedWorker,
        NativeWorkerLaunchPlan,
        NativeWorkerLauncher,
        NativeWorkerPolicy,
    )
    from .native_recipe_attempt import (
        NativeRecipeWorkerAttempt,
        NativeRecipeWorkerAttemptFactory,
        build_native_recipe_worker_attempt_factory,
    )
    from .native_win32 import (
        NativeWin32Error,
        NativeWin32ProcessFactory,
        Win32SuspendedWorker,
    )
    from .worker_provenance import (
        EXPECTED_WORKER_PATH,
        VerifiedRecipeWorker,
        WorkerProvenanceError,
        verify_active_worker,
        verify_installed_worker,
    )
    from .worker_runtime import (
        DEFAULT_MAX_MESSAGES,
        DEFAULT_WATCHDOG_TIMEOUT_MS,
        RecipeWorkerBrokerRuntime,
        WorkerRuntimeError,
        WorkerRuntimeReport,
    )
    from .recipes import (
        CalculatorPlan,
        CheckPlan,
        ImageTransformPlan,
        PrimitiveEvaluationError,
        RecipeValidationError,
        evaluate_calculator,
        evaluate_check,
        parse_calculator,
        parse_check,
        parse_image_transform,
    )
    from .repository import (
        ArtifactLimitError,
        ApprovalPolicyError,
        ApprovalTransitionError,
        DEFAULT_TERMINAL_JOB_RETENTION_SECONDS,
        ExecutionRepository,
        ExecutionCleanupResult,
        LeaseConflict,
        ExecutionRepositoryError,
    )
    from .cleanup import CleanupMetrics, CleanupSupervisor, ExecutionCleanupSupervisor
    from .recipe_coordinator import (
        DEFAULT_CANCEL_GRACE_SECONDS,
        DEFAULT_RECIPE_RETENTION_SECONDS,
        DEFAULT_WORKER_TIMEOUT_SECONDS,
        MAX_RECIPE_RETENTION_SECONDS,
        RECIPE_IMAGE_PROFILE,
        RECIPE_PAYLOAD_SCHEMA,
        RECIPE_RESULT_SCHEMA,
        RecipeExecutionCoordinator,
        RecipeExecutionError,
        RecipeImageRequest,
        RecipeWorkerAttempt,
        RecipeWorkerAttemptFactory,
        RecipeWorkerClient,
        RecipeWorkerConnection,
        RecipeWorkerOutput,
    )
    from .scratch_compute import (
        SCRATCH_COMPUTE_PROFILE,
        SCRATCH_PAYLOAD_SCHEMA,
        SCRATCH_RESULT_SCHEMA,
        ScratchComputeError,
        ScratchComputeRequest,
        ScratchComputeResult,
        evaluate_scratch_expression,
        extract_automatic_expression,
    )
    from .resource_accounting import (
        MAX_CONSOLE_BYTES,
        MAX_COUNTER,
        MAX_CPU_TIME_MS,
        MAX_MEMORY_BYTES,
        MAX_MESSAGES,
        MAX_OBSERVATION_BYTES,
        MAX_WALL_TIME_MS,
        MonotonicWatchdog,
        ResourceAccountingError,
        ResourceBudget,
        ResourceGovernor,
        ResourceSample,
        ResourceUsage,
    )
    from .release_gate import (
        ExternalReviewProbe,
        RecipeRuntimeReleaseGate,
        ReleaseGateCheck,
        ReleaseGateSnapshot,
    )
    from .release_attestation import (
        MAX_CLOCK_SKEW_SECONDS,
        MAX_REVIEW_ATTESTATION_BYTES,
        MAX_REVIEW_VALIDITY_SECONDS,
        RELEASE_REVIEW_SCHEMA,
        ReleaseReviewAttestation,
        ReleaseReviewProbe,
        ReleaseReviewTarget,
        ReleaseReviewVerificationError,
        TrustedReviewKeys,
        VerifiedReleaseReview,
        parse_release_review_attestation,
        verify_release_review,
    )


__all__ = [
    "ArtifactLimitError",
    "ArtifactBoundary",
    "ArtifactBoundaryError",
    "ArtifactSourceGrant",
    "ATTACHMENT_PAYLOAD_SCHEMA",
    "ATTACHMENT_RESULT_SCHEMA",
    "ATTACHMENT_STAGE_PROFILE",
    "AttachmentStageResult",
    "AttachmentStagingError",
    "AttachmentStagingService",
    "DEFAULT_ATTACHMENT_RETENTION_SECONDS",
    "MAX_ATTACHMENT_RETENTION_SECONDS",
    "ApprovalPolicyError",
    "ApprovalTransitionError",
    "BrokerAclPolicy",
    "BrokerFrame",
    "BrokerFrameDecoder",
    "BrokerMessage",
    "BrokerPeerPolicy",
    "BrokerProtocolError",
    "BrokerSessionKeys",
    "BundleInstallError",
    "BundleRecord",
    "DEFAULT_NATIVE_CONNECT_TIMEOUT_MS",
    "DEFAULT_NATIVE_PIPE_BUFFER_BYTES",
    "ExecutionRepository",
    "ExecutionCleanupResult",
    "ExecutionRepositoryError",
    "DEFAULT_TERMINAL_JOB_RETENTION_SECONDS",
    "CleanupMetrics",
    "CleanupSupervisor",
    "ExecutionCleanupSupervisor",
    "DEFAULT_CANCEL_GRACE_SECONDS",
    "DEFAULT_RECIPE_RETENTION_SECONDS",
    "DEFAULT_WORKER_TIMEOUT_SECONDS",
    "MAX_RECIPE_RETENTION_SECONDS",
    "RECIPE_IMAGE_PROFILE",
    "RECIPE_PAYLOAD_SCHEMA",
    "RECIPE_RESULT_SCHEMA",
    "RecipeExecutionCoordinator",
    "RecipeExecutionError",
    "RecipeImageRequest",
    "RecipeWorkerAttempt",
    "RecipeWorkerAttemptFactory",
    "RecipeWorkerClient",
    "RecipeWorkerConnection",
    "RecipeWorkerOutput",
    "ExecutionLifecycle",
    "LocalExecutionCoordinator",
    "LocalRecipeWorkerAttempt",
    "DEFAULT_CODE_TIMEOUT_SECONDS",
    "DEFAULT_CODE_STARTUP_TIMEOUT_SECONDS",
    "CODE_EXECUTION_PAYLOAD_SCHEMA",
    "CODE_EXECUTION_PROFILE",
    "CODE_EXECUTION_RESULT_SCHEMA",
    "CodeCapabilities",
    "CodeExecutionError",
    "CodeExecutionRequest",
    "CodeExecutionResult",
    "validate_code_source",
    "ExecutionProfile",
    "CoordinatorFactory",
    "build_recipe_coordinator_factory",
    "build_native_recipe_coordinator_factory",
    "CalculatorPlan",
    "CheckPlan",
    "FakeExecutionPlan",
    "FakeExecutionProvider",
    "ImageTransformPlan",
    "InstalledBundle",
    "KeyringUpdate",
    "LeaseConflict",
    "LifecycleSnapshot",
    "ManifestEntry",
    "ManifestState",
    "ManifestVerificationError",
    "MAX_ARTIFACT_PATH_CHARS",
    "MAX_OUTPUT_COUNT",
    "MAX_NATIVE_PIPE_NAME_LENGTH",
    "NativeBrokerClient",
    "NativeBrokerClientConfig",
    "NativeBrokerConnection",
    "NativeBrokerError",
    "NativeBrokerServer",
    "NativeBrokerServerConfig",
    "BrokerWorkerBinding",
    "BrokerWorkerBinder",
    "NativeBrokerIdentityBinder",
    "NativeLauncherError",
    "NativeProcessFactory",
    "NativeSuspendedWorker",
    "NativeWorkerLaunchPlan",
    "NativeWorkerLauncher",
    "NativeWorkerPolicy",
    "NativeRecipeWorkerAttempt",
    "NativeRecipeWorkerAttemptFactory",
    "build_native_recipe_worker_attempt_factory",
    "NativeWin32Error",
    "NativeWin32ProcessFactory",
    "Win32SuspendedWorker",
    "PrimitiveEvaluationError",
    "OutputClaim",
    "PublishedArtifact",
    "RecipeValidationError",
    "RuntimeHealth",
    "SCRATCH_COMPUTE_PROFILE",
    "SCRATCH_PAYLOAD_SCHEMA",
    "SCRATCH_RESULT_SCHEMA",
    "ScratchComputeError",
    "ScratchComputeRequest",
    "ScratchComputeResult",
    "evaluate_scratch_expression",
    "extract_automatic_expression",
    "ProviderHealthProbe",
    "QualificationLifecycleConfig",
    "QualificationProfileError",
    "build_execution_lifecycle",
    "parse_execution_profile",
    "RollbackAuthorizer",
    "SignedBundleInstaller",
    "SignedRecipeManifest",
    "TrustedRecipeKeys",
    "VerifiedRecipeManifest",
    "evaluate_calculator",
    "evaluate_check",
    "parse_signed_manifest",
    "parse_calculator",
    "parse_check",
    "parse_image_transform",
    "sniff_artifact_mime",
    "verify_bundle_files",
    "verify_manifest_signature",
    "parse_keyring_update",
    "verify_keyring_update",
    "verify_signed_manifest",
    "PeerIdentity",
    "authorize_message",
    "build_pipe_sddl",
    "EXPECTED_WORKER_PATH",
    "VerifiedRecipeWorker",
    "WorkerProvenanceError",
    "verify_active_worker",
    "verify_installed_worker",
    "DEFAULT_MAX_MESSAGES",
    "DEFAULT_WATCHDOG_TIMEOUT_MS",
    "RecipeWorkerBrokerRuntime",
    "WorkerRuntimeError",
    "WorkerRuntimeReport",
    "MAX_CONSOLE_BYTES",
    "MAX_COUNTER",
    "MAX_CPU_TIME_MS",
    "MAX_MEMORY_BYTES",
    "MAX_MESSAGES",
    "MAX_OBSERVATION_BYTES",
    "MAX_WALL_TIME_MS",
    "MonotonicWatchdog",
    "ResourceAccountingError",
    "ResourceBudget",
    "ResourceGovernor",
    "ResourceSample",
    "ResourceUsage",
    "ExternalReviewProbe",
    "RecipeRuntimeReleaseGate",
    "ReleaseGateCheck",
    "ReleaseGateSnapshot",
    "MAX_CLOCK_SKEW_SECONDS",
    "MAX_REVIEW_ATTESTATION_BYTES",
    "MAX_REVIEW_VALIDITY_SECONDS",
    "RELEASE_REVIEW_SCHEMA",
    "ReleaseReviewAttestation",
    "ReleaseReviewProbe",
    "ReleaseReviewTarget",
    "ReleaseReviewVerificationError",
    "TrustedReviewKeys",
    "VerifiedReleaseReview",
    "parse_release_review_attestation",
    "verify_release_review",
    "decode_frame",
    "decode_message",
    "encode_frame",
    "encode_message",
]


# Maps every name in __all__ to the submodule that defines it, so
# __getattr__ below can import only that one submodule on first access.
_LAZY_SUBMODULES: dict[str, str] = {
    # .broker
    "BrokerAclPolicy": "broker",
    "BrokerFrame": "broker",
    "BrokerFrameDecoder": "broker",
    "BrokerMessage": "broker",
    "BrokerPeerPolicy": "broker",
    "BrokerProtocolError": "broker",
    "BrokerSessionKeys": "broker",
    "PeerIdentity": "broker",
    "authorize_message": "broker",
    "decode_frame": "broker",
    "decode_message": "broker",
    "encode_frame": "broker",
    "encode_message": "broker",
    # .artifact_boundary
    "ArtifactBoundary": "artifact_boundary",
    "ArtifactBoundaryError": "artifact_boundary",
    "ArtifactSourceGrant": "artifact_boundary",
    "MAX_ARTIFACT_PATH_CHARS": "artifact_boundary",
    "MAX_OUTPUT_COUNT": "artifact_boundary",
    "OutputClaim": "artifact_boundary",
    "PublishedArtifact": "artifact_boundary",
    "sniff_artifact_mime": "artifact_boundary",
    # .attachment_staging
    "ATTACHMENT_PAYLOAD_SCHEMA": "attachment_staging",
    "ATTACHMENT_RESULT_SCHEMA": "attachment_staging",
    "ATTACHMENT_STAGE_PROFILE": "attachment_staging",
    "AttachmentStageResult": "attachment_staging",
    "AttachmentStagingError": "attachment_staging",
    "AttachmentStagingService": "attachment_staging",
    "DEFAULT_ATTACHMENT_RETENTION_SECONDS": "attachment_staging",
    "MAX_ATTACHMENT_RETENTION_SECONDS": "attachment_staging",
    # .fake
    "FakeExecutionPlan": "fake",
    "FakeExecutionProvider": "fake",
    # .bundle_installer
    "BundleInstallError": "bundle_installer",
    "BundleRecord": "bundle_installer",
    "InstalledBundle": "bundle_installer",
    "KeyringUpdate": "bundle_installer",
    "RollbackAuthorizer": "bundle_installer",
    "SignedBundleInstaller": "bundle_installer",
    "parse_keyring_update": "bundle_installer",
    "verify_keyring_update": "bundle_installer",
    # .lifecycle
    "ExecutionLifecycle": "lifecycle",
    "LifecycleSnapshot": "lifecycle",
    "RuntimeHealth": "lifecycle",
    # .local_runtime
    "DEFAULT_CODE_STARTUP_TIMEOUT_SECONDS": "local_runtime",
    "DEFAULT_CODE_TIMEOUT_SECONDS": "local_runtime",
    "LocalExecutionCoordinator": "local_runtime",
    "LocalRecipeWorkerAttempt": "local_runtime",
    # .code_execution
    "CODE_EXECUTION_PAYLOAD_SCHEMA": "code_execution",
    "CODE_EXECUTION_PROFILE": "code_execution",
    "CODE_EXECUTION_RESULT_SCHEMA": "code_execution",
    "CodeCapabilities": "code_execution",
    "CodeExecutionError": "code_execution",
    "CodeExecutionRequest": "code_execution",
    "CodeExecutionResult": "code_execution",
    "validate_code_source": "code_execution",
    # .qualification
    "CoordinatorFactory": "qualification",
    "ExecutionProfile": "qualification",
    "ProviderHealthProbe": "qualification",
    "QualificationLifecycleConfig": "qualification",
    "QualificationProfileError": "qualification",
    "build_execution_lifecycle": "qualification",
    "build_native_recipe_coordinator_factory": "qualification",
    "build_recipe_coordinator_factory": "qualification",
    "parse_execution_profile": "qualification",
    # .manifest
    "ManifestEntry": "manifest",
    "ManifestState": "manifest",
    "ManifestVerificationError": "manifest",
    "SignedRecipeManifest": "manifest",
    "TrustedRecipeKeys": "manifest",
    "VerifiedRecipeManifest": "manifest",
    "parse_signed_manifest": "manifest",
    "verify_bundle_files": "manifest",
    "verify_manifest_signature": "manifest",
    "verify_signed_manifest": "manifest",
    # .native_broker
    "DEFAULT_NATIVE_CONNECT_TIMEOUT_MS": "native_broker",
    "DEFAULT_NATIVE_PIPE_BUFFER_BYTES": "native_broker",
    "MAX_NATIVE_PIPE_NAME_LENGTH": "native_broker",
    "NativeBrokerClient": "native_broker",
    "NativeBrokerClientConfig": "native_broker",
    "NativeBrokerConnection": "native_broker",
    "NativeBrokerError": "native_broker",
    "NativeBrokerServer": "native_broker",
    "NativeBrokerServerConfig": "native_broker",
    "build_pipe_sddl": "native_broker",
    # .native_launcher
    "BrokerWorkerBinding": "native_launcher",
    "BrokerWorkerBinder": "native_launcher",
    "NativeBrokerIdentityBinder": "native_launcher",
    "NativeLauncherError": "native_launcher",
    "NativeProcessFactory": "native_launcher",
    "NativeSuspendedWorker": "native_launcher",
    "NativeWorkerLaunchPlan": "native_launcher",
    "NativeWorkerLauncher": "native_launcher",
    "NativeWorkerPolicy": "native_launcher",
    # .native_recipe_attempt
    "NativeRecipeWorkerAttempt": "native_recipe_attempt",
    "NativeRecipeWorkerAttemptFactory": "native_recipe_attempt",
    "build_native_recipe_worker_attempt_factory": "native_recipe_attempt",
    # .native_win32
    "NativeWin32Error": "native_win32",
    "NativeWin32ProcessFactory": "native_win32",
    "Win32SuspendedWorker": "native_win32",
    # .worker_provenance
    "EXPECTED_WORKER_PATH": "worker_provenance",
    "VerifiedRecipeWorker": "worker_provenance",
    "WorkerProvenanceError": "worker_provenance",
    "verify_active_worker": "worker_provenance",
    "verify_installed_worker": "worker_provenance",
    # .worker_runtime
    "DEFAULT_MAX_MESSAGES": "worker_runtime",
    "DEFAULT_WATCHDOG_TIMEOUT_MS": "worker_runtime",
    "RecipeWorkerBrokerRuntime": "worker_runtime",
    "WorkerRuntimeError": "worker_runtime",
    "WorkerRuntimeReport": "worker_runtime",
    # .recipes
    "CalculatorPlan": "recipes",
    "CheckPlan": "recipes",
    "ImageTransformPlan": "recipes",
    "PrimitiveEvaluationError": "recipes",
    "RecipeValidationError": "recipes",
    "evaluate_calculator": "recipes",
    "evaluate_check": "recipes",
    "parse_calculator": "recipes",
    "parse_check": "recipes",
    "parse_image_transform": "recipes",
    # .repository
    "ArtifactLimitError": "repository",
    "ApprovalPolicyError": "repository",
    "ApprovalTransitionError": "repository",
    "DEFAULT_TERMINAL_JOB_RETENTION_SECONDS": "repository",
    "ExecutionRepository": "repository",
    "ExecutionCleanupResult": "repository",
    "LeaseConflict": "repository",
    "ExecutionRepositoryError": "repository",
    # .cleanup
    "CleanupMetrics": "cleanup",
    "CleanupSupervisor": "cleanup",
    "ExecutionCleanupSupervisor": "cleanup",
    # .recipe_coordinator
    "DEFAULT_CANCEL_GRACE_SECONDS": "recipe_coordinator",
    "DEFAULT_RECIPE_RETENTION_SECONDS": "recipe_coordinator",
    "DEFAULT_WORKER_TIMEOUT_SECONDS": "recipe_coordinator",
    "MAX_RECIPE_RETENTION_SECONDS": "recipe_coordinator",
    "RECIPE_IMAGE_PROFILE": "recipe_coordinator",
    "RECIPE_PAYLOAD_SCHEMA": "recipe_coordinator",
    "RECIPE_RESULT_SCHEMA": "recipe_coordinator",
    "RecipeExecutionCoordinator": "recipe_coordinator",
    "RecipeExecutionError": "recipe_coordinator",
    "RecipeImageRequest": "recipe_coordinator",
    "RecipeWorkerAttempt": "recipe_coordinator",
    "RecipeWorkerAttemptFactory": "recipe_coordinator",
    "RecipeWorkerClient": "recipe_coordinator",
    "RecipeWorkerConnection": "recipe_coordinator",
    "RecipeWorkerOutput": "recipe_coordinator",
    # .scratch_compute
    "SCRATCH_COMPUTE_PROFILE": "scratch_compute",
    "SCRATCH_PAYLOAD_SCHEMA": "scratch_compute",
    "SCRATCH_RESULT_SCHEMA": "scratch_compute",
    "ScratchComputeError": "scratch_compute",
    "ScratchComputeRequest": "scratch_compute",
    "ScratchComputeResult": "scratch_compute",
    "evaluate_scratch_expression": "scratch_compute",
    "extract_automatic_expression": "scratch_compute",
    # .resource_accounting
    "MAX_CONSOLE_BYTES": "resource_accounting",
    "MAX_COUNTER": "resource_accounting",
    "MAX_CPU_TIME_MS": "resource_accounting",
    "MAX_MEMORY_BYTES": "resource_accounting",
    "MAX_MESSAGES": "resource_accounting",
    "MAX_OBSERVATION_BYTES": "resource_accounting",
    "MAX_WALL_TIME_MS": "resource_accounting",
    "MonotonicWatchdog": "resource_accounting",
    "ResourceAccountingError": "resource_accounting",
    "ResourceBudget": "resource_accounting",
    "ResourceGovernor": "resource_accounting",
    "ResourceSample": "resource_accounting",
    "ResourceUsage": "resource_accounting",
    # .release_gate
    "ExternalReviewProbe": "release_gate",
    "RecipeRuntimeReleaseGate": "release_gate",
    "ReleaseGateCheck": "release_gate",
    "ReleaseGateSnapshot": "release_gate",
    # .release_attestation
    "MAX_CLOCK_SKEW_SECONDS": "release_attestation",
    "MAX_REVIEW_ATTESTATION_BYTES": "release_attestation",
    "MAX_REVIEW_VALIDITY_SECONDS": "release_attestation",
    "RELEASE_REVIEW_SCHEMA": "release_attestation",
    "ReleaseReviewAttestation": "release_attestation",
    "ReleaseReviewProbe": "release_attestation",
    "ReleaseReviewTarget": "release_attestation",
    "ReleaseReviewVerificationError": "release_attestation",
    "TrustedReviewKeys": "release_attestation",
    "VerifiedReleaseReview": "release_attestation",
    "parse_release_review_attestation": "release_attestation",
    "verify_release_review": "release_attestation",
}


def __getattr__(name: str) -> Any:
    try:
        submodule_name = _LAZY_SUBMODULES[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    module = import_module(f".{submodule_name}", __name__)
    value = getattr(module, name)
    # Cache on the package module object so a second access of the same name
    # is a plain attribute lookup, never re-entering __getattr__.
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(__all__)
