"""Durable execution primitives and provider-independent safety contracts.

Only the deterministic fake provider and reviewed broker contracts are exposed in
this phase. The native adapter remains transport-only; real runtime providers stay
absent until later ADR gates are approved.
"""

from .broker import (
    BrokerAclPolicy,
    BrokerFrame,
    BrokerFrameDecoder,
    BrokerMessage,
    BrokerPeerPolicy,
    BrokerProtocolError,
    BrokerSessionKeys,
    PeerIdentity,
    authorize_message,
    decode_frame,
    decode_message,
    encode_frame,
    encode_message,
)
from .fake import FakeExecutionPlan, FakeExecutionProvider
from .lifecycle import ExecutionLifecycle, LifecycleSnapshot, RuntimeHealth
from .manifest import (
    ManifestEntry,
    ManifestState,
    ManifestVerificationError,
    SignedRecipeManifest,
    TrustedRecipeKeys,
    VerifiedRecipeManifest,
    parse_signed_manifest,
    verify_bundle_files,
    verify_signed_manifest,
)
from .native_broker import (
    DEFAULT_NATIVE_CONNECT_TIMEOUT_MS,
    DEFAULT_NATIVE_PIPE_BUFFER_BYTES,
    MAX_NATIVE_PIPE_NAME_LENGTH,
    NativeBrokerClient,
    NativeBrokerClientConfig,
    NativeBrokerConnection,
    NativeBrokerError,
    NativeBrokerServer,
    NativeBrokerServerConfig,
    build_pipe_sddl,
)
from .recipes import (
    CalculatorPlan,
    CheckPlan,
    ImageTransformPlan,
    PrimitiveEvaluationError,
    RecipeValidationError,
    evaluate_calculator,
    evaluate_check,
    parse_calculator,
    parse_check,
    parse_image_transform,
)
from .repository import (
    ArtifactLimitError,
    ApprovalPolicyError,
    ApprovalTransitionError,
    ExecutionRepository,
    LeaseConflict,
    ExecutionRepositoryError,
)

__all__ = [
    "ArtifactLimitError",
    "ApprovalPolicyError",
    "ApprovalTransitionError",
    "BrokerAclPolicy",
    "BrokerFrame",
    "BrokerFrameDecoder",
    "BrokerMessage",
    "BrokerPeerPolicy",
    "BrokerProtocolError",
    "BrokerSessionKeys",
    "DEFAULT_NATIVE_CONNECT_TIMEOUT_MS",
    "DEFAULT_NATIVE_PIPE_BUFFER_BYTES",
    "ExecutionRepository",
    "ExecutionRepositoryError",
    "ExecutionLifecycle",
    "CalculatorPlan",
    "CheckPlan",
    "FakeExecutionPlan",
    "FakeExecutionProvider",
    "ImageTransformPlan",
    "LeaseConflict",
    "LifecycleSnapshot",
    "ManifestEntry",
    "ManifestState",
    "ManifestVerificationError",
    "MAX_NATIVE_PIPE_NAME_LENGTH",
    "NativeBrokerClient",
    "NativeBrokerClientConfig",
    "NativeBrokerConnection",
    "NativeBrokerError",
    "NativeBrokerServer",
    "NativeBrokerServerConfig",
    "PrimitiveEvaluationError",
    "RecipeValidationError",
    "RuntimeHealth",
    "SignedRecipeManifest",
    "TrustedRecipeKeys",
    "VerifiedRecipeManifest",
    "evaluate_calculator",
    "evaluate_check",
    "parse_signed_manifest",
    "parse_calculator",
    "parse_check",
    "parse_image_transform",
    "verify_bundle_files",
    "verify_signed_manifest",
    "PeerIdentity",
    "authorize_message",
    "build_pipe_sddl",
    "decode_frame",
    "decode_message",
    "encode_frame",
    "encode_message",
]
