"""Regenerate the checked-in OpenAPI and initial TypeScript contracts."""

from __future__ import annotations

import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from cortex_backend.api import create_app  # noqa: E402
from cortex_backend.api.schemas import ExecutionSSEEvent  # noqa: E402


CONTRACT_DIR = ROOT / "contracts"
OPENAPI_PATH = CONTRACT_DIR / "openapi.json"
TYPESCRIPT_PATH = CONTRACT_DIR / "cortex-api.ts"


def main() -> None:
    CONTRACT_DIR.mkdir(parents=True, exist_ok=True)
    app = create_app(allowed_hosts=("127.0.0.1", "localhost", "::1"))
    specification = app.openapi()
    # StreamingResponse does not automatically register the JSON envelope
    # carried by text/event-stream. Keep that shared client contract generated
    # from the Pydantic model rather than maintaining a hand-written tail.
    schemas = specification.setdefault("components", {}).setdefault("schemas", {})
    schemas["ExecutionSSEEvent"] = ExecutionSSEEvent.model_json_schema(
        ref_template="#/components/schemas/{model}"
    )
    OPENAPI_PATH.write_text(
        json.dumps(specification, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    TYPESCRIPT_PATH.write_text(render_typescript(specification), encoding="utf-8")


def render_typescript(specification: dict[str, Any]) -> str:
    schemas = specification.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by tools/generate_contracts.py. Do not edit manually.",
        "// The web client consumes this generated contract.",
        "",
    ]
    for name, schema in schemas.items():
        lines.append(f"export interface {name} {{")
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        for property_name, property_schema in properties.items():
            optional = "" if property_name in required else "?"
            lines.append(
                f"  {property_name}{optional}: {_typescript_type(property_schema)};"
            )
        lines.extend(["}", ""])
    return "\n".join(lines)


def _typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "anyOf" in schema:
        return " | ".join(_typescript_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_typescript_type(item) for item in schema["oneOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _typescript_type(schema.get("items", {}))
        return f"Array<{item_type}>"
    if schema_type == "object":
        if "additionalProperties" in schema and isinstance(
            schema["additionalProperties"], dict
        ):
            return f"Record<string, {_typescript_type(schema['additionalProperties'])}>"
        return "Record<string, unknown>"
    if schema_type == "null":
        return "null"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
    }.get(schema_type, "unknown")


if __name__ == "__main__":
    main()
